name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/pt-gpt
            git pull
            wall "Pulled latest version."
            npm install
            wall "Installed any new dependencies."
            cd frontend
            npm install
            wall "Installed any new dependencies for frontend."
            npx expo build:web
            wall "Built new version of frontend."
            pm2 restart app
            wall "✔️Deployed new version of PT-GPT\n"
