name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/pt-gpt
            git pull
            wall "Pulled latest version." -n
            npm install
            wall "Installed any new dependencies." -n
            cd frontend
            npm install
            wall "Installed any new dependencies for frontend." -n
            npx expo export:web
            wall "Built new version of frontend." -n
            pm2 restart app
            wall "✔️Deployed new version of PT-GPT\n" -n
